print("Hello")
# print(4 + 5.5)

# x, y = 6, 10
# print(x - y)
# print(x + y)
# print(x * y)
# print(x ** 2)
# print(y ** x)
# print(y / 3)
# print(x % y)
# print(y // 3)
# print(y % x)
# print(y % y)
# print(y / y)
# print(-5 / 2)
# print(-5 // 2)
# print(y > x)
# print(x > y)
# print(y == x)
# print(y != x)
# print(y >= x)
# print(x <= y)